name: Build and Push Docker Image

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use the GitHub Actions actor as username
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN secret

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ lower(github.repository) }}:latest
            ghcr.io/${{ lower(github.repository) }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ lower(github.repository) }} # Apply lowercase here too for cache scope
          cache-to: type=gha,mode=max,scope=${{ lower(github.repository) }} # Apply lowercase here too


      # Optional: If you want to remove the local images after push (to save space on the runner)
      # - name: Clean up images
      #   run: docker image prune -a -f --filter "until=24h"
