name: Build and Push Docker Image

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Action to set up Docker Buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use the GitHub Actions actor as username
          password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN secret

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5 # Action to build and push the image
        with:
          context: . # Build context is the root of the repository
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Push the image to the registry
          tags: |
            ghcr.io/${{ github.repository }}:latest # Tag with latest
            ghcr.io/${{ github.repository }}:${{ github.sha }} # Tag with commit SHA
          cache-from: type=gha # Enable caching from previous builds
          cache-to: type=gha,mode=max # Enable caching for future builds


      # Optional: If you want to remove the local images after push (to save space on the runner)
      # - name: Clean up images
      #   run: docker image prune -a -f --filter "until=24h"
